LotteryWebAppFiles/admin/views.py
# IMPORTS
from flask import Blueprint, render_template, request, flash
from app import db
from models import User, Draw

# CONFIG
admin_blueprint = Blueprint('admin', __name__, template_folder='templates')


# VIEWS
# view admin homepage
@admin_blueprint.route('/admin')
def admin():
    return render_template('admin.html', name="PLACEHOLDER FOR FIRSTNAME")


# view all registered users
@admin_blueprint.route('/view_all_users', methods=['POST'])
def view_all_users():
    return render_template('admin.html', name="PLACEHOLDER FOR FIRSTNAME",
                           current_users=User.query.filter_by(role='user').all())


# create a new winning draw
@admin_blueprint.route('/create_winning_draw', methods=['POST'])
def create_winning_draw():

    # get current winning draw
    current_winning_draw = Draw.query.filter_by(win=True).first()
    round = 1

    # if a current winning draw exists
    if current_winning_draw:
        # update lottery round by 1
        round = current_winning_draw.round + 1

        # delete current winning draw
        db.session.delete(current_winning_draw)
        db.session.commit()

    # get new winning draw entered in form
    submitted_draw = ''
    for i in range(6):
        submitted_draw += request.form.get('no' + str(i + 1)) + ' '
    # remove any surrounding whitespace
    submitted_draw.strip()

    # create a new draw object with the form data.
    new_winning_draw = Draw(user_id=0, draw=submitted_draw, win=True, round=round)

    # add the new winning draw to the database
    db.session.add(new_winning_draw)
    db.session.commit()

    # re-render admin page
    flash("New winning draw added.")
    return admin()


# view current winning draw
@admin_blueprint.route('/view_winning_draw', methods=['POST'])
def view_winning_draw():

    # get winning draw from DB
    current_winning_draw = Draw.query.filter_by(win=True).first()

    # if a winning draw exists
    if current_winning_draw:
        # re-render admin page with current winning draw and lottery round
        return render_template('admin.html', winning_draw=current_winning_draw, name="PLACEHOLDER FOR FIRSTNAME")

    # if no winning draw exists, rerender admin page
    flash("No winning draw exists. Please add winning draw.")
    return admin()


# view lottery results and winners
@admin_blueprint.route('/run_lottery', methods=['POST'])
def run_lottery():

    # get current unplayed winning draw
    current_winning_draw = Draw.query.filter_by(win=True, played=False).first()

    # if current unplayed winning draw exists
    if current_winning_draw:

        # get all unplayed user draws
        user_draws = Draw.query.filter_by(win=False, played=False).all()
        results = []

        # if at least one unplayed user draw exists
        if user_draws:

            # update current winning draw as played
            current_winning_draw.played = True
            db.session.add(current_winning_draw)
            db.session.commit()

            # for each unplayed user draw
            for draw in user_draws:

                # get the owning user (instance/object)
                user = User.query.filter_by(id=draw.user_id).first()

                # if user draw matches current unplayed winning draw
                if draw.draw == current_winning_draw.draw:

                    # add details of winner to list of results
                    results.append((current_winning_draw.round, draw.draw, draw.user_id, user.email))

                    # update draw as a winning draw (this will be used to highlight winning draws in the user's
                    # lottery page)
                    draw.match = True

                # update draw as played
                draw.played = True

                # update draw with current lottery round
                draw.round = current_winning_draw.round

                # commit draw changes to DB
                db.session.add(draw)
                db.session.commit()

            # if no winners
            if len(results) == 0:
                flash("No winners.")

            return render_template('admin.html', results=results, name="PLACEHOLDER FOR FIRSTNAME")

        flash("No user draws entered.")
        return admin()

    # if current unplayed winning draw does not exist
    flash("Current winning draw expired. Add new winning draw for next round.")
    return admin()


# view last 10 log entries
@admin_blueprint.route('/logs', methods=['POST'])
def logs():
    with open("lottery.log", "r") as f:
        content = f.read().splitlines()[-10:]
        content.reverse()

    return render_template('admin.html', logs=content, name="PLACEHOLDER FOR FIRSTNAME")

LotteryWebAppFiles/lottery/views.py
# IMPORTS
import logging

from flask import Blueprint, render_template, request, flash

from app import db
from models import Draw

# CONFIG
lottery_blueprint = Blueprint('lottery', __name__, template_folder='templates')


# VIEWS
# view lottery page
@lottery_blueprint.route('/lottery')
def lottery():
    return render_template('lottery.html')


@lottery_blueprint.route('/add_draw', methods=['POST'])
def add_draw():
    submitted_draw = ''
    for i in range(6):
        submitted_draw += request.form.get('no' + str(i + 1)) + ' '
    submitted_draw.strip()

    # create a new draw with the form data.
    new_draw = Draw(user_id=1, draw=submitted_draw, win=False, round=0)  # TODO: update user_id [user_id=1 is a placeholder]

    # add the new draw to the database
    db.session.add(new_draw)
    db.session.commit()

    # re-render lottery.page
    flash('Draw %s submitted.' % submitted_draw)
    return lottery()


# view all draws that have not been played
@lottery_blueprint.route('/view_draws', methods=['POST'])
def view_draws():
    # get all draws that have not been played [played=0]
    playable_draws = Draw.query.filter_by(played=False).all()  # TODO: filter playable draws for current user

    # if playable draws exist
    if len(playable_draws) != 0:
        # re-render lottery page with playable draws
        return render_template('lottery.html', playable_draws=playable_draws)
    else:
        flash('No playable draws.')
        return lottery()


# view lottery results
@lottery_blueprint.route('/check_draws', methods=['POST'])
def check_draws():
    # get played draws
    played_draws = Draw.query.filter_by(played=True).all()  # TODO: filter played draws for current user

    # if played draws exist
    if len(played_draws) != 0:
        return render_template('lottery.html', results=played_draws, played=True)

    # if no played draws exist [all draw entries have been played therefore wait for next lottery round]
    else:
        flash("Next round of lottery yet to play. Check you have playable draws.")
        return lottery()


# delete all played draws
@lottery_blueprint.route('/play_again', methods=['POST'])
def play_again():
    delete_played = Draw.__table__.delete().where(Draw.played)  # TODO: delete played draws for current user only
    db.session.execute(delete_played)
    db.session.commit()

    flash("All played draws deleted.")
    return lottery()

LotteryWebAppFiles/users/views.py
# IMPORTS
import logging
from functools import wraps

from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import current_user

from app import db
from models import User
from users.forms import RegisterForm

# CONFIG
users_blueprint = Blueprint('users', __name__, template_folder='templates')


# VIEWS
# view registration
@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    # create signup form object
    form = RegisterForm()

    # if request method is POST or form is valid
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # if this returns a user, then the email already exists in database

        # if email already exists redirect user back to signup page with error message so user can try again
        if user:
            flash('Email address already exists')
            return render_template('register.html', form=form)

        # create a new user with the form data
        new_user = User(email=form.email.data,
                        firstname=form.firstname.data,
                        lastname=form.lastname.data,
                        phone=form.phone.data,
                        password=form.password.data,
                        pin_key=form.pin_key.data,
                        role='user')

        # add the new user to the database
        db.session.add(new_user)
        db.session.commit()

        # sends user to login page
        return redirect(url_for('users.login'))
    # if request method is GET or form not valid re-render signup page
    return render_template('register.html', form=form)


# view user login
@users_blueprint.route('/login')
def login():
    return render_template('login.html')


# view user profile
@users_blueprint.route('/profile')
def profile():
    return render_template('profile.html', name="PLACEHOLDER FOR FIRSTNAME")


# view user account
@users_blueprint.route('/account')
def account():
    return render_template('account.html',
                           acc_no="PLACEHOLDER FOR USER ID",
                           email="PLACEHOLDER FOR USER EMAIL",
                           firstname="PLACEHOLDER FOR USER FIRSTNAME",
                           lastname="PLACEHOLDER FOR USER LASTNAME",
                           phone="PLACEHOLDER FOR USER PHONE")

LotteryWebAppFiles/templates/account.html
{% extends "base.html" %}

{% block content %}

<div class="column is-6 is-offset-3">
    <h3 class="title">Your Account</h3>
    <div class="box">
        <table class="table">
        <tbody>
            <tr>
                <th>Account No.</th>
                <th>{{ acc_no }}</th>
            </tr>
            <tr>
                <th>Email</th>
                <th>{{ email }}</th>
            </tr>
            <tr>
                <th>First Name</th>
                <th>{{ firstname }}</th>
            </tr>
            <tr>
                <th>Last Name</th>
                <th>{{ lastname }}</th>
            </tr>
            <tr>
                <th>Phone No.</th>
                <th>{{ phone }}</th>
            </tr>
        </tbody>
        </table>
    </div>
</div>


{% endblock %}

LotteryWebAppFiles/templates/admin.html
{% extends "base.html" %}

{% block content %}
    <script type="text/javascript" src="{{ url_for('static', filename='rng.js') }}"></script>
    <h3 class="title is-3">Lottery Web Application Admin
    </h3>
    <h4 class="subtitle is-4">
        Welcome, {{ name }}
    </h4>

    <div class="column is-10 is-offset-1">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="notification is-danger">
                    {{ messages[0] }}
                </div>
            {% endif %}
        {% endwith %}


        <h4 class="title is-4">Current Users</h4>
        <div class="box">
            {% if current_users %}
                <div class="field">
                    <table class="table">
                        <tr>
                            <th>ID</th>
                            <th>Email</th>
                            <th>Firstname</th>
                            <th>Lastname</th>
                            <th>Phone No.</th>
                            <th>Role</th>
                        </tr>
                        {% for user in current_users %}
                            <tr>
                                <td>{{ user.id }}</td>
                                <td>{{ user.email }}</td>
                                <td>{{ user.firstname }}</td>
                                <td>{{ user.lastname }}</td>
                                <td>{{ user.phone }}</td>
                                <td>{{ user.role }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            {% endif %}
            <form method="POST" action="/view_all_users">
                <div>
                    <button class="button is-info is-centered">View All Users</button>
                </div>
            </form>
        </div>
    </div>
    <div class="column is-8 is-offset-2">
        <h4 class="title is-4">Create Winning Draw</h4>
        <div class="box">
            <form method="POST" action="/create_winning_draw">
                <div class="columns is-multiline is-centered">
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no1" id="no1" placeholder="value 1">
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no2" id="no2" placeholder="value 2">
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no3" id="no3" placeholder="value 3">
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no4" id="no4" placeholder="value 4">
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no5" id="no5" placeholder="value 5">
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no6" id="no6" placeholder="value 6">
                    </div>
                </div>
                <div class="field">
                    <button type="button" class="button is-info is-centered" onclick="luckyDip()">Lucky
                        Dip
                    </button>
                </div>
                <div>
                    <button class="button is-info is-centered">Submit Winning Draw</button>
                </div>

            </form>
        </div>
    </div>
    <div class="column is-4 is-offset-4">
        <h4 class="title is-4">Current Winning Draw</h4>
        <div class="box">
            {% if winning_draw %}
                <div class="field">
                    <p>Round {{ winning_draw.round }}</p>
                    <p>{{ winning_draw.draw }}</p>
                </div>
            {% endif %}
            <form method="POST" action="/view_winning_draw">
                <div>
                    <button class="button is-info is-centered">View Winning Draw</button>
                </div>
            </form>
        </div>
    </div>
    <div class="column is-8 is-offset-2">
        <h4 class="title is-4">Run Lottery</h4>
        <div class="box">
            {% if results %}
                <div class="field">
                    {% for result in results %}
                        <p>{{ result }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <form method="POST" action="/run_lottery">
                <div>
                    <button class="button is-info is-centered">View Winners</button>
                </div>
            </form>
        </div>
    </div>
    <div class="column is-8 is-offset-2" id="test">
        <h4 class="title is-4">Security Logs</h4>
        <div class="box">
            {% if logs %}
                <div class="field">
                <table class="table">
                    <tr>
                        <th>Last 10 Security Log Entries</th>
                    </tr>
                    {% for entry in logs %}
                        <tr>
                            <td>{{ entry }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}
            <form method="POST" action="/logs">
                <div>
                    <button class="button is-info is-centered">View Logs</button>
                </div>
            </form>
            </div>
        </div>


{% endblock %}

LotteryWebAppFiles/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CSC2031</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>

    <style>
    .table {
      margin-left: auto;
      margin-right: auto;
    }
    </style>

    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                       <div class="navbar-end">
                            <a href="{{ url_for('index') }}" class="navbar-item">
                               Home
                            </a>
                                <a href="{{ url_for('users.profile') }}" class="navbar-item">
                                    Profile
                                </a>
                                <a href="{{ url_for('lottery.lottery') }}" class="navbar-item">
                                    Lottery
                                </a>

                                <a href="{{ url_for('admin.admin') }}" class="navbar-item">
                                    Admin
                                </a>
                                {#TODO: LOGIN#}
                                <a href="" class="navbar-item">
                                    Login
                                </a>
                                <a href="{{ url_for('users.register') }}" class="navbar-item">
                                    Register
                                </a>
                                 <a href="{{ url_for('users.account') }}" class="navbar-item">
                                    Account
                                </a>
                                {#TODO: LOGOUT#}
                                <a href="" class="navbar-item">
                                    Logout
                                </a>

                       </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

LotteryWebAppFiles/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">Lottery Web Application
</h1>
<h2 class="subtitle">
  CSC2031 Security & Programming Paradigms
</h2>

{#TODO: ADD NAME AND STUDENT NUMBER#}
<p>Name ('Student Number')</p>
{% endblock %}

LotteryWebAppFiles/templates/login.html
{% extends "base.html" %}

{% block content %}

    <h3 class="title is-3">Login</h3>

    <p>TODO</p>

{% endblock %}

LotteryWebAppFiles/templates/lottery.html
{% extends "base.html" %}

{% block content %}
    <script type="text/javascript" src="{{ url_for('static', filename='rng.js') }}"></script>
    <h3 class="title is-3">
        Lottery
    </h3>
    <div class="column is-8 is-offset-2">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="notification is-danger">
                    {{ messages[0] }}
                </div>
            {% endif %}
        {% endwith %}
        <h4 class="title is-4">Create Draw</h4>
        <div class="box">

            <form method="POST" action="/add_draw">
                <div class="columns is-multiline is-centered">
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no1" id="no1" placeholder="value 1">
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no2" id="no2" placeholder="value 2">
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no3" id="no3" placeholder="value 3">
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no4" id="no4" placeholder="value 4">
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no5" id="no5" placeholder="value 5">
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no6" id="no6" placeholder="value 6">
                    </div>
                </div>
                <div class="field">
                    <button type="button" class="button is-info is-centered" onclick="luckyDip()">Lucky
                        Dip
                    </button>
                </div>
                <div class="field">
                    <button class="button is-info is-centered">Submit Draw</button>
                </div>
            </form>
        </div>
    </div>
    <div class="column is-4 is-offset-4">
        <h4 class="title is-4">Playable Draws</h4>
        <div class="box">
            {% if playable_draws %}
                <div class="field">

                    {# render playable draws #}
                    {% for draw in playable_draws %}
                        <p>{{ draw.draw }}</p>
                    {% endfor %}

                </div>
            {% endif %}
            <form method="POST" action="/view_draws">
                <div>
                    <button class="button is-info is-centered">View Playable Draws</button>
                </div>
            </form>
        </div>
    </div>
    <div class="column is-6 is-offset-3">
        <h4 class="title is-4">Play Lottery</h4>
        <div class="box">
            {% if results %}
                <div class="field">
                    <table class="table">
                        <tr>
                            <th>Round</th>
                            <th>Draw</th>
                            <th>Played</th>
                            <th>Win</th>
                        </tr>

                        {# render results #}
                        {% for draw in results %}
                            <tr>
                                <td>{{ draw.round }}</td>
                                <td>{{ draw.draw }}</td>
                                <td>{{ draw.played }}</td>
                                {% if draw.win %}
                                    <td style="background-color: yellow">{{ draw.win }}</td>
                                {% else %}
                                    <td>{{ draw.win }}</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            {% endif %}

            {# render check result button if current lottery round not played #}
            {% if not played %}
                <form method="POST" action="/check_draws">
                    <div>
                        <button class="button is-info is-centered">Check Result</button>
                    </div>
                </form>
            {% else %}
                {# render play again button if current lottery round has been played #}
                <form method="POST" action="/play_again">
                    <div>
                        <button class="button is-info is-centered">Play Again</button>
                    </div>
                </form>
            {% endif %}
        </div>
    </div>

{% endblock %}

LotteryWebAppFiles/templates/profile.html
{% extends "base.html" %}

{% block content %}

<h1 class="title">
  Welcome, {{ name }}
</h1>

{% endblock %}

LotteryWebAppFiles/templates/register.html
{% extends "base.html" %}

{% block content %}
    <div class="column is-5 is-offset-4">
        <h3 class="title is-3">Register</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}. Go to <a href="{{ url_for('users.login') }}">login page</a>.
                    </div>
                {% endif %}
            {% endwith %}
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.email(class="input", placeholder="Email") }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.firstname(class="input", placeholder="First Name") }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.lastname(class="input", placeholder="Last Name") }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.phone(class="input", placeholder="Phone") }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.password(class="input", placeholder="Password") }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.confirm_password(class="input", placeholder="Confirm Password") }}
                    </div>

                </div>
                <div class="field">
                    <div class="control">
                        {{ form.pin_key(class="input", placeholder="PIN Key") }}
                    </div>
                    <div>
                        {# TODO: Add PIN generation setup instructions #}
                    </div>

                </div>


                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}